### PR TITLE
Closes #3 fixes some last remnants/references to "gsm" files that were migrated

### LINKED ISSUE #3: Pkgdown failure after first try of removal of qualification testing
There was a workflow that would only on deployments of the dev branch with some path references to the gsm package

### PR DESCRIPTION
**Pull request by zdz2101**
Fixes references to files in `gsm` that no longer exist and were migrated, not caught until deployment/push onto dev branch

### CODE REVIEW

File: inst/qualification/qualification_map.R [hunk 1]
```diff
@@ -41,7 +41,7 @@ qualification_map <- function(
   })
 
   ### Read in specs spreadsheet
-  spec <- read.csv(system.file("qualification", "qualification_specs.csv", package = "gsm"))
+  spec <- read.csv(system.file("qualification", "qualification_specs.csv", package = "gsm.qc"))
```
Comment (zdz2101) [inline inst/qualification/qualification_map.R:44]: @lauramaxwell I believe this was causing some funkiness in the push to dev earlier this morning
